spring:
  application:
    name: codereviewer
  mongodb:
    uri: mongodb://qwiklabs-gcp-02-7c289c9c79d4:JBf4jXvr63zBhesXkZCPkEXxFcb3mC79o_UN7UOZqlPy7JSA@00d1e3ce-e7a1-4375-a3b9-8439b5096258.nam5.firestore.goog:443/user-review-profile?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false


  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:AQ.Ab8RN6IzLawy246bNWx8P0Z-5nMOsz-26T3stZZWxCWgDxZ4Fg}
        chat:
          model: gemini-3.6-flash

github:
  api:
    url: https://api.github.com
  token: ${GITHUB_TOKEN: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}
