spring:
  application:
    name: codereviewer
  data:
    mongodb:
      uri: ${MONGODB_URI}

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.6-flash

server:
  port: 8081 

github:
  api:
    url: https://api.github.com
  token: ${GITHUB_TOKEN}
